### ISSUE TITLE
Can i training with scale 1.5x ?

### ISSUE THREAD

**Issue by NgdHung31** [the-database/traiNNer-redux#126]
Hi, 

First of all, thank you for your incredible work on this project! I really enjoy using it and appreciate all the effort that has gone into it.

I’m currently facing a problem while trying to upscale images from **720p to 1080p**. Here’s the challenge I’m encountering:

- I’ve tried using a simple x2 upscale from 720p, which looks visually good.
- However, when I subsequently **downscale to 1080p**, I notice that the quality, color fidelity, and smoothness degrade significantly. 

My question is:
1. Are there any specific techniques or configurations within this project that I could use to achieve better results for this kind of task?
2. Alternatively, is there a particular **architecture or model** you’d recommend that excels at upscaling to **non-standard ratios** (like 720p to 1080p) without quality loss?

Thank you so much in advance for your guidance. I’d appreciate any advice or suggestions from the community!

Best regards

**Comment by the-database** [comment]
Hi, thanks for the kind words. 1.5x scale is currently not possible with any of the available architectures in traiNNer redux. 

The simplest solution would be to train 2x and downscale as you already did. Are you able to share the details of exactly how you performed the downscale, along with some sample inputs and outputs that show the degraded results when you downscale to 1080p? I may be able to help you get better results on the downscale step.

For my own reference, here is a paper (https://arxiv.org/abs/2303.04336) which proposes a strategy for a 1.5x scale implementation, in theory this strategy could be applied to modify any of the existing architectures to support 1.5x scale. Models trained on modified architectured wouldn't be compatible with 3rd party tools like chaiNNer, unless the onnx conversion script is used to convert the pytorch model to onnx first.

**Comment by NgdHung31** [comment]
Thanks for your published articles, I will try to research that article.

**Comment by the-database** [comment]
Some additional reading, if we go down this rabbithole: https://github.com/Weepingchestnut/Arbitrary-Scale-SR

traiNNer-redux currently only supports single scale models. Supporting arbitrary scale models would allow support for 1.5x (along with all other scales).
